### ISSUE TITLE
getting my dropdown to select a particular group of records from my table

### ISSUE THREAD

**Issue by maitrishah25** [maitrishah25/cheesy_burritos#1]
trying out some ideas, would like to talk thru my ideas and get it written properly

**Comment by amadden80** [comment]
Please add more details regarding the issue.

**Comment by maitrishah25** [comment]
I'm trying to work out the correct way to select the group from my table, and also to render it onto the page. So far I've been trying out things like:

burritos = FoodItem.find_by_category("burritos")

burritos = FoodItem.find(:condition => :category = "burritos")

and then trying to display it on the html page by burritos.name. 

I have something, but not really sure where I'm going wrong...

**Comment by maitrishah25** [comment]
I got it!!!!! I wouldn't mind still meeting to clean up and go through what I have.
