### ISSUE TITLE
params

### ISSUE THREAD

**Issue by maitrishah25** [maitrishah25/cheesy_burritos#2]
I'm having issues with referencing the id of the food-items within my accordion table. It's getting thrown off because I have them sectioned off based on categories, but then I need to connect the ID from the food-items table. For example, when I click to add a veggie burrito to my order, it displays as a beef fajita...and so on.

Can I pls get some help?

**Comment by rapala61** [comment]
Push your latest changes so i can see your code

**Comment by maitrishah25** [comment]
I just pushed it

**Comment by rapala61** [comment]
in person
