### ISSUE TITLE
page to display all receipts hitting an error for another route in my controller

### ISSUE THREAD

**Issue by maitrishah25** [maitrishah25/cheesy_burritos#4]
Had an issue with displaying all of the receipts. I set up a page to display all of the receipts as an accordion, showing the table number and party id, and when selected, drops down to show the entire receipt. From there, the server has the option to hit paid.

When I set this up, my error says that in my parties controller, it can't find a party with an id of editall and references a route for a different page. Trying to figure out what the issue is. Is this one of those things where the order of the routes in the controller page is making a difference?

I pushed my latest version so you can see my code.

**Comment by emilylordahl** [comment]
It could be an issue with the order of your routes. An ID should be an integer, not `editall`! Try what Andrew just suggested this morning by using `puts params` in the route that is breaking to see if you are getting the values from the params hash that you want.

Using an `/editall` route could work, but it does not really meet RESTful conventions. What is the overall goal of using an `/editall` route?

**Comment by emilylordahl** [comment]
Was this issue resolved?

**Comment by maitrishah25** [comment]
Semi-resolved. Fixed some things but not others..

**Comment by emilylordahl** [comment]
Ok, cool. That's usually how it goes! :smile: I'll close this for now.
