### ISSUE TITLE
deciphering error for total price for an order 

### ISSUE THREAD

**Issue by maitrishah25** [maitrishah25/cheesy_burritos#5]
I'm having a hard time getting my sum function working. This is what I have in my controller and I get an undefined method + for nil:nilclass...

```
@item_order = ItemOrder.create(params[:item_order])
food_item = FoodItem.find(@item_order.food_item_id)
party = Party.find(@item_order.party_id)

party.bill_subt += food_item.price

party.update({
      bill_subt: party.bill_subt
    })
```

**Comment by maitrishah25** [comment]
Hi guys, still haven't figured out the sum. Referencing the variables is getting messy because my routes are complicated. Can we please meet in person today?

I think I might redo the project today/this weekend to build up from the routes, instead of down from the flowchart I made...so the routes are clearer.

**Comment by amadden80** [comment]
_in person_
